Models/CD.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EF_MOM_3_2.Models
{
	public class CD
	{
        public int CDId { get; set; }
		[Required]
        public string? Album { get; set; }

		public int? ArtistId { get; set; }
		public Artist? Artist { get; set; }
		public int? CustomerId { get; set; }
		public Customer? Customer { get; set; }

		public DateTime? DateLent { get; set; } = null;

		public CD()
		{
		}
	}
}

Controllers/CDController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EF_MOM_3_2.Data;
using EF_MOM_3_2.Models;

namespace EF_MOM_3_2.Controllers
{
    public class CDController : Controller
    {
        private readonly DataContext _context;

        public CDController(DataContext context)
        {
            _context = context;
        }

        // GET: CD
        public async Task<IActionResult> Index(string search)
        {
            var dataContext = _context.CD.Include(c => c.Artist).Include(c => c.Customer);
            if (!String.IsNullOrEmpty(search))
            {
                var result = await dataContext.Where(CD => CD.Album.ToLower().Contains(search.ToLower())).ToListAsync();
                return View(result);
            }
            else
            {
                var result = await dataContext.ToListAsync();
                return View(result);
            }
        }

        // GET: CD/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Include(c => c.Artist)
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.CDId == id);
            if (cD == null)
            {
                return NotFound();
            }

            return View(cD);
        }

        // GET: CD/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId");
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId");
            return View();
        }

        // POST: CD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CDId,Album,ArtistId,CustomerId,DateLent")] CD cD)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cD);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", cD.CustomerId);
            return View(cD);
        }

        // GET: CD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cD = await _context.CD.FindAsync(id);
            if (cD == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", cD.CustomerId);
            return View(cD);
        }

        // POST: CD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CDId,Album,ArtistId,CustomerId,DateLent")] CD cD)
        {
            if (id != cD.CDId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cD);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CDExists(cD.CDId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", cD.CustomerId);
            return View(cD);
        }

        // GET: CD/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Include(c => c.Artist)
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.CDId == id);
            if (cD == null)
            {
                return NotFound();
            }

            return View(cD);
        }

        // POST: CD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cD = await _context.CD.FindAsync(id);
            _context.CD.Remove(cD);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CDExists(int id)
        {
            return _context.CD.Any(e => e.CDId == id);
        }
    }
}

Views/CD/Create.cshtml
@model EF_MOM_3_2.Models.CD

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CD</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class ="form-control" asp-items="ViewBag.ArtistId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DateLent" class="control-label"></label>
                <input asp-for="DateLent" class="form-control" />
                <span asp-validation-for="DateLent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CD/Delete.cshtml
@model EF_MOM_3_2.Models.CD

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.ArtistId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateLent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateLent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CDId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CD/Details.cshtml
@model EF_MOM_3_2.Models.CD

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateLent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateLent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CDId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CD/Edit.cshtml
@model EF_MOM_3_2.Models.CD

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CD</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CDId" />
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateLent" class="control-label"></label>
                <input asp-for="DateLent" class="form-control" />
                <span asp-validation-for="DateLent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CD/Index.cshtml
@model IEnumerable<EF_MOM_3_2.Models.CD>

@{
    ViewData["Title"] = "Albums";
}

<h1>Albums</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form id="searchForm" asp-controller="CD" asp-action="index">
    <label>CD name:</label>
    <input type="text" name="search" />
    <input type="submit" value="Search" />
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CDId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateLent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CDId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Album)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateLent)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CDId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CDId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CDId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>